var annotated_dup =
[
    [ "com", null, [
      [ "facebook", null, [
        [ "thrift", null, [
          [ "annotations", null, [
            [ "Sensitive", "interfacecom_1_1facebook_1_1thrift_1_1annotations_1_1Sensitive.html", null ]
          ] ],
          [ "async", null, [
            [ "AsyncMethodCallback", "interfacecom_1_1facebook_1_1thrift_1_1async_1_1AsyncMethodCallback.html", "interfacecom_1_1facebook_1_1thrift_1_1async_1_1AsyncMethodCallback" ],
            [ "TAsyncClient", "classcom_1_1facebook_1_1thrift_1_1async_1_1TAsyncClient.html", "classcom_1_1facebook_1_1thrift_1_1async_1_1TAsyncClient" ],
            [ "TAsyncClientFactory", "interfacecom_1_1facebook_1_1thrift_1_1async_1_1TAsyncClientFactory.html", "interfacecom_1_1facebook_1_1thrift_1_1async_1_1TAsyncClientFactory" ],
            [ "TAsyncClientManager", "classcom_1_1facebook_1_1thrift_1_1async_1_1TAsyncClientManager.html", "classcom_1_1facebook_1_1thrift_1_1async_1_1TAsyncClientManager" ],
            [ "TAsyncMethodCall", "classcom_1_1facebook_1_1thrift_1_1async_1_1TAsyncMethodCall.html", "classcom_1_1facebook_1_1thrift_1_1async_1_1TAsyncMethodCall" ]
          ] ],
          [ "meta_data", null, [
            [ "FieldMetaData", "classcom_1_1facebook_1_1thrift_1_1meta__data_1_1FieldMetaData.html", "classcom_1_1facebook_1_1thrift_1_1meta__data_1_1FieldMetaData" ],
            [ "FieldValueMetaData", "classcom_1_1facebook_1_1thrift_1_1meta__data_1_1FieldValueMetaData.html", "classcom_1_1facebook_1_1thrift_1_1meta__data_1_1FieldValueMetaData" ],
            [ "ListMetaData", "classcom_1_1facebook_1_1thrift_1_1meta__data_1_1ListMetaData.html", "classcom_1_1facebook_1_1thrift_1_1meta__data_1_1ListMetaData" ],
            [ "MapMetaData", "classcom_1_1facebook_1_1thrift_1_1meta__data_1_1MapMetaData.html", "classcom_1_1facebook_1_1thrift_1_1meta__data_1_1MapMetaData" ],
            [ "SetMetaData", "classcom_1_1facebook_1_1thrift_1_1meta__data_1_1SetMetaData.html", "classcom_1_1facebook_1_1thrift_1_1meta__data_1_1SetMetaData" ],
            [ "StructMetaData", "classcom_1_1facebook_1_1thrift_1_1meta__data_1_1StructMetaData.html", "classcom_1_1facebook_1_1thrift_1_1meta__data_1_1StructMetaData" ]
          ] ],
          [ "protocol", null, [
            [ "TBinaryProtocol", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TBinaryProtocol.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TBinaryProtocol" ],
            [ "TCompactJSONProtocol", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TCompactJSONProtocol.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TCompactJSONProtocol" ],
            [ "TCompactProtocol", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TCompactProtocol.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TCompactProtocol" ],
            [ "TField", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TField.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TField" ],
            [ "THeaderProtocol", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1THeaderProtocol.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1THeaderProtocol" ],
            [ "TJSONProtocol", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TJSONProtocol.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TJSONProtocol" ],
            [ "TJSONProtocolBase", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TJSONProtocolBase.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TJSONProtocolBase" ],
            [ "TList", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TList.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TList" ],
            [ "TMap", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TMap.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TMap" ],
            [ "TMessage", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TMessage.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TMessage" ],
            [ "TMessageType", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TMessageType.html", null ],
            [ "TMultiplexedProtocol", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TMultiplexedProtocol.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TMultiplexedProtocol" ],
            [ "TProtocol", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TProtocol.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TProtocol" ],
            [ "TProtocolDecorator", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TProtocolDecorator.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TProtocolDecorator" ],
            [ "TProtocolException", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TProtocolException.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TProtocolException" ],
            [ "TProtocolFactory", "interfacecom_1_1facebook_1_1thrift_1_1protocol_1_1TProtocolFactory.html", "interfacecom_1_1facebook_1_1thrift_1_1protocol_1_1TProtocolFactory" ],
            [ "TProtocolUtil", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TProtocolUtil.html", null ],
            [ "TSet", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TSet.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TSet" ],
            [ "TSimpleJSONProtocol", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TSimpleJSONProtocol.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TSimpleJSONProtocol" ],
            [ "TStruct", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TStruct.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TStruct" ],
            [ "TTupleProtocol", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TTupleProtocol.html", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TTupleProtocol" ],
            [ "TType", "classcom_1_1facebook_1_1thrift_1_1protocol_1_1TType.html", null ]
          ] ],
          [ "scheme", null, [
            [ "IScheme", "interfacecom_1_1facebook_1_1thrift_1_1scheme_1_1IScheme.html", "interfacecom_1_1facebook_1_1thrift_1_1scheme_1_1IScheme" ],
            [ "SchemeFactory", "interfacecom_1_1facebook_1_1thrift_1_1scheme_1_1SchemeFactory.html", "interfacecom_1_1facebook_1_1thrift_1_1scheme_1_1SchemeFactory" ],
            [ "StandardScheme", "classcom_1_1facebook_1_1thrift_1_1scheme_1_1StandardScheme.html", null ],
            [ "TupleScheme", "classcom_1_1facebook_1_1thrift_1_1scheme_1_1TupleScheme.html", null ]
          ] ],
          [ "server", null, [
            [ "example", null, [
              [ "TSimpleServer", "classcom_1_1facebook_1_1thrift_1_1server_1_1example_1_1TSimpleServer.html", "classcom_1_1facebook_1_1thrift_1_1server_1_1example_1_1TSimpleServer" ],
              [ "TThreadPoolServer", "classcom_1_1facebook_1_1thrift_1_1server_1_1example_1_1TThreadPoolServer.html", "classcom_1_1facebook_1_1thrift_1_1server_1_1example_1_1TThreadPoolServer" ]
            ] ],
            [ "TConnectionContext", "classcom_1_1facebook_1_1thrift_1_1server_1_1TConnectionContext.html", "classcom_1_1facebook_1_1thrift_1_1server_1_1TConnectionContext" ],
            [ "THsHaServer", "classcom_1_1facebook_1_1thrift_1_1server_1_1THsHaServer.html", "classcom_1_1facebook_1_1thrift_1_1server_1_1THsHaServer" ],
            [ "TNonblockingServer", "classcom_1_1facebook_1_1thrift_1_1server_1_1TNonblockingServer.html", "classcom_1_1facebook_1_1thrift_1_1server_1_1TNonblockingServer" ],
            [ "TRpcConnectionContext", "classcom_1_1facebook_1_1thrift_1_1server_1_1TRpcConnectionContext.html", "classcom_1_1facebook_1_1thrift_1_1server_1_1TRpcConnectionContext" ],
            [ "TServer", "classcom_1_1facebook_1_1thrift_1_1server_1_1TServer.html", "classcom_1_1facebook_1_1thrift_1_1server_1_1TServer" ],
            [ "TServlet", "classcom_1_1facebook_1_1thrift_1_1server_1_1TServlet.html", "classcom_1_1facebook_1_1thrift_1_1server_1_1TServlet" ],
            [ "TThreadFactoryImpl", "classcom_1_1facebook_1_1thrift_1_1server_1_1TThreadFactoryImpl.html", "classcom_1_1facebook_1_1thrift_1_1server_1_1TThreadFactoryImpl" ]
          ] ],
          [ "transport", null, [
            [ "OkHttp3Util", "classcom_1_1facebook_1_1thrift_1_1transport_1_1OkHttp3Util.html", null ],
            [ "TFramedTransport", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TFramedTransport.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TFramedTransport" ],
            [ "THeaderException", "classcom_1_1facebook_1_1thrift_1_1transport_1_1THeaderException.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1THeaderException" ],
            [ "THeaderTransport", "classcom_1_1facebook_1_1thrift_1_1transport_1_1THeaderTransport.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1THeaderTransport" ],
            [ "THttp2Client", "classcom_1_1facebook_1_1thrift_1_1transport_1_1THttp2Client.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1THttp2Client" ],
            [ "THttpClient", "classcom_1_1facebook_1_1thrift_1_1transport_1_1THttpClient.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1THttpClient" ],
            [ "TIOStreamTransport", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TIOStreamTransport.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TIOStreamTransport" ],
            [ "TMemoryBuffer", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TMemoryBuffer.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TMemoryBuffer" ],
            [ "TMemoryInputTransport", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TMemoryInputTransport.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TMemoryInputTransport" ],
            [ "TNonblockingServerSocket", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TNonblockingServerSocket.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TNonblockingServerSocket" ],
            [ "TNonblockingServerTransport", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TNonblockingServerTransport.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TNonblockingServerTransport" ],
            [ "TNonblockingSocket", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TNonblockingSocket.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TNonblockingSocket" ],
            [ "TNonblockingTransport", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TNonblockingTransport.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TNonblockingTransport" ],
            [ "TServerSocket", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TServerSocket.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TServerSocket" ],
            [ "TServerTransport", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TServerTransport.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TServerTransport" ],
            [ "TSocket", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TSocket.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TSocket" ],
            [ "TSocketIf", "interfacecom_1_1facebook_1_1thrift_1_1transport_1_1TSocketIf.html", "interfacecom_1_1facebook_1_1thrift_1_1transport_1_1TSocketIf" ],
            [ "TTransport", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TTransport.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TTransport" ],
            [ "TTransportException", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TTransportException.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TTransportException" ],
            [ "TTransportFactory", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TTransportFactory.html", "classcom_1_1facebook_1_1thrift_1_1transport_1_1TTransportFactory" ]
          ] ],
          [ "utils", null, [
            [ "ByteBufferUtils", "classcom_1_1facebook_1_1thrift_1_1utils_1_1ByteBufferUtils.html", null ],
            [ "Logger", "classcom_1_1facebook_1_1thrift_1_1utils_1_1Logger.html", "classcom_1_1facebook_1_1thrift_1_1utils_1_1Logger" ],
            [ "StandardCharsets", "classcom_1_1facebook_1_1thrift_1_1utils_1_1StandardCharsets.html", null ]
          ] ],
          [ "EncodingUtils", "classcom_1_1facebook_1_1thrift_1_1EncodingUtils.html", null ],
          [ "EventHandlerBase", "classcom_1_1facebook_1_1thrift_1_1EventHandlerBase.html", "classcom_1_1facebook_1_1thrift_1_1EventHandlerBase" ],
          [ "IntRangeSet", "classcom_1_1facebook_1_1thrift_1_1IntRangeSet.html", "classcom_1_1facebook_1_1thrift_1_1IntRangeSet" ],
          [ "MultipleTProcessorEventHandlers", "classcom_1_1facebook_1_1thrift_1_1MultipleTProcessorEventHandlers.html", "classcom_1_1facebook_1_1thrift_1_1MultipleTProcessorEventHandlers" ],
          [ "ShortStack", "classcom_1_1facebook_1_1thrift_1_1ShortStack.html", "classcom_1_1facebook_1_1thrift_1_1ShortStack" ],
          [ "TApplicationException", "classcom_1_1facebook_1_1thrift_1_1TApplicationException.html", "classcom_1_1facebook_1_1thrift_1_1TApplicationException" ],
          [ "TBase", "interfacecom_1_1facebook_1_1thrift_1_1TBase.html", "interfacecom_1_1facebook_1_1thrift_1_1TBase" ],
          [ "TBaseHelper", "classcom_1_1facebook_1_1thrift_1_1TBaseHelper.html", null ],
          [ "TByteArrayOutputStream", "classcom_1_1facebook_1_1thrift_1_1TByteArrayOutputStream.html", "classcom_1_1facebook_1_1thrift_1_1TByteArrayOutputStream" ],
          [ "TClientIf", "interfacecom_1_1facebook_1_1thrift_1_1TClientIf.html", "interfacecom_1_1facebook_1_1thrift_1_1TClientIf" ],
          [ "TDeserializer", "classcom_1_1facebook_1_1thrift_1_1TDeserializer.html", "classcom_1_1facebook_1_1thrift_1_1TDeserializer" ],
          [ "TDeserializeUtils", "classcom_1_1facebook_1_1thrift_1_1TDeserializeUtils.html", null ],
          [ "TEnum", "interfacecom_1_1facebook_1_1thrift_1_1TEnum.html", "interfacecom_1_1facebook_1_1thrift_1_1TEnum" ],
          [ "TException", "classcom_1_1facebook_1_1thrift_1_1TException.html", "classcom_1_1facebook_1_1thrift_1_1TException" ],
          [ "TFieldIdEnum", "interfacecom_1_1facebook_1_1thrift_1_1TFieldIdEnum.html", "interfacecom_1_1facebook_1_1thrift_1_1TFieldIdEnum" ],
          [ "TFieldRequirementType", "classcom_1_1facebook_1_1thrift_1_1TFieldRequirementType.html", null ],
          [ "TMultiplexedProcessor", "classcom_1_1facebook_1_1thrift_1_1TMultiplexedProcessor.html", "classcom_1_1facebook_1_1thrift_1_1TMultiplexedProcessor" ],
          [ "TProcessor", "interfacecom_1_1facebook_1_1thrift_1_1TProcessor.html", "interfacecom_1_1facebook_1_1thrift_1_1TProcessor" ],
          [ "TProcessorEventHandler", "classcom_1_1facebook_1_1thrift_1_1TProcessorEventHandler.html", "classcom_1_1facebook_1_1thrift_1_1TProcessorEventHandler" ],
          [ "TProcessorFactory", "classcom_1_1facebook_1_1thrift_1_1TProcessorFactory.html", "classcom_1_1facebook_1_1thrift_1_1TProcessorFactory" ],
          [ "TSerializer", "classcom_1_1facebook_1_1thrift_1_1TSerializer.html", "classcom_1_1facebook_1_1thrift_1_1TSerializer" ],
          [ "TServiceClient", "classcom_1_1facebook_1_1thrift_1_1TServiceClient.html", "classcom_1_1facebook_1_1thrift_1_1TServiceClient" ],
          [ "TUnion< Me extends TUnion", "classcom_1_1facebook_1_1thrift_1_1TUnion_3_01Me_01extends_01TUnion.html", null ],
          [ "UserExceptionHandler", "classcom_1_1facebook_1_1thrift_1_1UserExceptionHandler.html", "classcom_1_1facebook_1_1thrift_1_1UserExceptionHandler" ]
        ] ]
      ] ],
      [ "vesoft", null, [
        [ "nebula", "namespacecom_1_1vesoft_1_1nebula.html", [
          [ "client", null, [
            [ "graph", null, [
              [ "data", null, [
                [ "BaseDataObject", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1BaseDataObject.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1BaseDataObject" ],
                [ "CASignedSSLParam", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1CASignedSSLParam.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1CASignedSSLParam" ],
                [ "CoordinateWrapper", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1CoordinateWrapper.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1CoordinateWrapper" ],
                [ "DateTimeWrapper", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1DateTimeWrapper.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1DateTimeWrapper" ],
                [ "DateWrapper", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1DateWrapper.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1DateWrapper" ],
                [ "DurationWrapper", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1DurationWrapper.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1DurationWrapper" ],
                [ "GeographyWrapper", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1GeographyWrapper.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1GeographyWrapper" ],
                [ "HostAddress", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1HostAddress.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1HostAddress" ],
                [ "LineStringWrapper", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1LineStringWrapper.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1LineStringWrapper" ],
                [ "Node", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1Node.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1Node" ],
                [ "PathWrapper", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1PathWrapper.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1PathWrapper" ],
                [ "PointWrapper", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1PointWrapper.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1PointWrapper" ],
                [ "PolygonWrapper", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1PolygonWrapper.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1PolygonWrapper" ],
                [ "Relationship", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1Relationship.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1Relationship" ],
                [ "ResultSet", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1ResultSet.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1ResultSet" ],
                [ "SelfSignedSSLParam", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1SelfSignedSSLParam.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1SelfSignedSSLParam" ],
                [ "SSLParam", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1SSLParam.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1SSLParam" ],
                [ "TimeUtil", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1TimeUtil.html", null ],
                [ "TimeWrapper", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1TimeWrapper.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1TimeWrapper" ],
                [ "ValueWrapper", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1ValueWrapper.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1ValueWrapper" ],
                [ "TestData", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1TestData.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1TestData" ],
                [ "TestDataFromServer", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1TestDataFromServer.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1data_1_1TestDataFromServer" ]
              ] ],
              [ "exception", null, [
                [ "AuthFailedException", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1AuthFailedException.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1AuthFailedException" ],
                [ "BindSpaceFailedException", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1BindSpaceFailedException.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1BindSpaceFailedException" ],
                [ "ClientServerIncompatibleException", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1ClientServerIncompatibleException.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1ClientServerIncompatibleException" ],
                [ "InvalidConfigException", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1InvalidConfigException.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1InvalidConfigException" ],
                [ "InvalidSessionException", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1InvalidSessionException.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1InvalidSessionException" ],
                [ "InvalidValueException", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1InvalidValueException.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1InvalidValueException" ],
                [ "IOErrorException", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1IOErrorException.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1IOErrorException" ],
                [ "NotValidConnectionException", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1NotValidConnectionException.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1exception_1_1NotValidConnectionException" ]
              ] ],
              [ "net", null, [
                [ "AuthResult", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1AuthResult.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1AuthResult" ],
                [ "Connection", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1Connection.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1Connection" ],
                [ "ConnObjectPool", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1ConnObjectPool.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1ConnObjectPool" ],
                [ "LoadBalancer", "interfacecom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1LoadBalancer.html", "interfacecom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1LoadBalancer" ],
                [ "NebulaPool", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1NebulaPool.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1NebulaPool" ],
                [ "RoundRobinLoadBalancer", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1RoundRobinLoadBalancer.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1RoundRobinLoadBalancer" ],
                [ "Session", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1Session.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1Session" ],
                [ "SessionsManager", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1SessionsManager.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1SessionsManager" ],
                [ "SessionState", "enumcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1SessionState.html", "enumcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1SessionState" ],
                [ "SessionWrapper", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1SessionWrapper.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1SessionWrapper" ],
                [ "SyncConnection", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1SyncConnection.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1SyncConnection" ],
                [ "TestConnectionPool", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1TestConnectionPool.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1TestConnectionPool" ],
                [ "TestGraphServiceClient", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1TestGraphServiceClient.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1TestGraphServiceClient" ],
                [ "TestSession", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1TestSession.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1TestSession" ],
                [ "TestSessionPool", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1TestSessionPool.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1TestSessionPool" ],
                [ "TestSessionsManager", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1TestSessionsManager.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1TestSessionsManager" ],
                [ "TestSyncConnection", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1TestSyncConnection.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1net_1_1TestSyncConnection" ]
              ] ],
              [ "NebulaPoolConfig", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1NebulaPoolConfig.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1NebulaPoolConfig" ],
              [ "NebulaSession", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1NebulaSession.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1NebulaSession" ],
              [ "SessionPool", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1SessionPool.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1SessionPool" ],
              [ "SessionPoolConfig", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1SessionPoolConfig.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1SessionPoolConfig" ],
              [ "SessionsManagerConfig", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1SessionsManagerConfig.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1graph_1_1SessionsManagerConfig" ]
            ] ],
            [ "meta", null, [
              [ "exception", null, [
                [ "ExecuteFailedException", "classcom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1exception_1_1ExecuteFailedException.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1exception_1_1ExecuteFailedException" ]
              ] ],
              [ "AbstractMetaClient", "classcom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1AbstractMetaClient.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1AbstractMetaClient" ],
              [ "MetaCache", "interfacecom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1MetaCache.html", "interfacecom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1MetaCache" ],
              [ "MetaClient", "classcom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1MetaClient.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1MetaClient" ],
              [ "MetaManager", "classcom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1MetaManager.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1MetaManager" ],
              [ "MockNebulaGraph", "classcom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1MockNebulaGraph.html", null ],
              [ "TestMetaClient", "classcom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1TestMetaClient.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1TestMetaClient" ],
              [ "TestMetaManager", "classcom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1TestMetaManager.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1meta_1_1TestMetaManager" ]
            ] ],
            [ "storage", null, [
              [ "data", null, [
                [ "BaseTableRow", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1data_1_1BaseTableRow.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1data_1_1BaseTableRow" ],
                [ "EdgeRow", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1data_1_1EdgeRow.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1data_1_1EdgeRow" ],
                [ "EdgeTableRow", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1data_1_1EdgeTableRow.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1data_1_1EdgeTableRow" ],
                [ "ScanStatus", "enumcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1data_1_1ScanStatus.html", "enumcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1data_1_1ScanStatus" ],
                [ "VertexRow", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1data_1_1VertexRow.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1data_1_1VertexRow" ],
                [ "VertexTableRow", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1data_1_1VertexTableRow.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1data_1_1VertexTableRow" ]
              ] ],
              [ "processor", null, [
                [ "EdgeProcessor", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1processor_1_1EdgeProcessor.html", null ],
                [ "VertexProcessor", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1processor_1_1VertexProcessor.html", null ],
                [ "EdgeProcessorTest", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1processor_1_1EdgeProcessorTest.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1processor_1_1EdgeProcessorTest" ],
                [ "VertexProcessorTest", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1processor_1_1VertexProcessorTest.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1processor_1_1VertexProcessorTest" ]
              ] ],
              [ "scan", null, [
                [ "PartScanInfo", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1PartScanInfo.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1PartScanInfo" ],
                [ "PartScanQueue", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1PartScanQueue.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1PartScanQueue" ],
                [ "ScanEdgeResult", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1ScanEdgeResult.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1ScanEdgeResult" ],
                [ "ScanEdgeResultIterator", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1ScanEdgeResultIterator.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1ScanEdgeResultIterator" ],
                [ "ScanResultIterator", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1ScanResultIterator.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1ScanResultIterator" ],
                [ "ScanVertexResult", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1ScanVertexResult.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1ScanVertexResult" ],
                [ "ScanVertexResultIterator", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1ScanVertexResultIterator.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1ScanVertexResultIterator" ],
                [ "PartScanQueueTest", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1PartScanQueueTest.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1scan_1_1PartScanQueueTest" ]
              ] ],
              [ "GraphStorageConnection", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1GraphStorageConnection.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1GraphStorageConnection" ],
              [ "StorageClient", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1StorageClient.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1StorageClient" ],
              [ "StorageConnPool", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1StorageConnPool.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1StorageConnPool" ],
              [ "StorageConnPoolFactory", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1StorageConnPoolFactory.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1StorageConnPoolFactory" ],
              [ "StoragePoolConfig", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1StoragePoolConfig.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1StoragePoolConfig" ],
              [ "MockStorageData", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1MockStorageData.html", null ],
              [ "MockUtil", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1MockUtil.html", null ],
              [ "StorageClientTest", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1StorageClientTest.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1StorageClientTest" ],
              [ "StorageConnPoolTest", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1StorageConnPoolTest.html", "classcom_1_1vesoft_1_1nebula_1_1client_1_1storage_1_1StorageConnPoolTest" ]
            ] ],
            [ "util", null, [
              [ "ProcessUtil", "classcom_1_1vesoft_1_1nebula_1_1client_1_1util_1_1ProcessUtil.html", null ]
            ] ]
          ] ],
          [ "encoder", null, [
            [ "NebulaCodec", "interfacecom_1_1vesoft_1_1nebula_1_1encoder_1_1NebulaCodec.html", "interfacecom_1_1vesoft_1_1nebula_1_1encoder_1_1NebulaCodec" ],
            [ "NebulaCodecImpl", "classcom_1_1vesoft_1_1nebula_1_1encoder_1_1NebulaCodecImpl.html", "classcom_1_1vesoft_1_1nebula_1_1encoder_1_1NebulaCodecImpl" ],
            [ "RowWriter", "interfacecom_1_1vesoft_1_1nebula_1_1encoder_1_1RowWriter.html", "interfacecom_1_1vesoft_1_1nebula_1_1encoder_1_1RowWriter" ],
            [ "RowWriterImpl", "classcom_1_1vesoft_1_1nebula_1_1encoder_1_1RowWriterImpl.html", "classcom_1_1vesoft_1_1nebula_1_1encoder_1_1RowWriterImpl" ],
            [ "SchemaProvider", "interfacecom_1_1vesoft_1_1nebula_1_1encoder_1_1SchemaProvider.html", "interfacecom_1_1vesoft_1_1nebula_1_1encoder_1_1SchemaProvider" ],
            [ "SchemaProviderImpl", "classcom_1_1vesoft_1_1nebula_1_1encoder_1_1SchemaProviderImpl.html", "classcom_1_1vesoft_1_1nebula_1_1encoder_1_1SchemaProviderImpl" ],
            [ "MetaCacheImplTest", "classcom_1_1vesoft_1_1nebula_1_1encoder_1_1MetaCacheImplTest.html", "classcom_1_1vesoft_1_1nebula_1_1encoder_1_1MetaCacheImplTest" ],
            [ "TestEncoder", "classcom_1_1vesoft_1_1nebula_1_1encoder_1_1TestEncoder.html", "classcom_1_1vesoft_1_1nebula_1_1encoder_1_1TestEncoder" ]
          ] ],
          [ "examples", null, [
            [ "GraphClientExample", "classcom_1_1vesoft_1_1nebula_1_1examples_1_1GraphClientExample.html", null ],
            [ "GraphSessionPoolExample", "classcom_1_1vesoft_1_1nebula_1_1examples_1_1GraphSessionPoolExample.html", null ],
            [ "GraphSessionPoolWithHttp2Example", "classcom_1_1vesoft_1_1nebula_1_1examples_1_1GraphSessionPoolWithHttp2Example.html", null ],
            [ "StorageClientExample", "classcom_1_1vesoft_1_1nebula_1_1examples_1_1StorageClientExample.html", null ]
          ] ],
          [ "graph", "namespacecom_1_1vesoft_1_1nebula_1_1graph.html", [
            [ "AuthResponse", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1AuthResponse.html", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1AuthResponse" ],
            [ "ExecutionResponse", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1ExecutionResponse.html", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1ExecutionResponse" ],
            [ "GraphService", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1GraphService.html", [
              [ "AsyncIface", "interfacecom_1_1vesoft_1_1nebula_1_1graph_1_1GraphService_1_1AsyncIface.html", "interfacecom_1_1vesoft_1_1nebula_1_1graph_1_1GraphService_1_1AsyncIface" ],
              [ "Iface", "interfacecom_1_1vesoft_1_1nebula_1_1graph_1_1GraphService_1_1Iface.html", "interfacecom_1_1vesoft_1_1nebula_1_1graph_1_1GraphService_1_1Iface" ]
            ] ],
            [ "Pair", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1Pair.html", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1Pair" ],
            [ "PlanDescription", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1PlanDescription.html", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1PlanDescription" ],
            [ "PlanNodeBranchInfo", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1PlanNodeBranchInfo.html", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1PlanNodeBranchInfo" ],
            [ "PlanNodeDescription", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1PlanNodeDescription.html", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1PlanNodeDescription" ],
            [ "ProfilingStats", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1ProfilingStats.html", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1ProfilingStats" ],
            [ "VerifyClientVersionReq", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1VerifyClientVersionReq.html", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1VerifyClientVersionReq" ],
            [ "VerifyClientVersionResp", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1VerifyClientVersionResp.html", "classcom_1_1vesoft_1_1nebula_1_1graph_1_1VerifyClientVersionResp" ]
          ] ],
          [ "meta", "namespacecom_1_1vesoft_1_1nebula_1_1meta.html", [
            [ "AddHostsIntoZoneReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AddHostsIntoZoneReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AddHostsIntoZoneReq" ],
            [ "AddHostsReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AddHostsReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AddHostsReq" ],
            [ "AddListenerReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AddListenerReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AddListenerReq" ],
            [ "AdminJobReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AdminJobReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AdminJobReq" ],
            [ "AdminJobResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AdminJobResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AdminJobResp" ],
            [ "AdminJobResult", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AdminJobResult.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AdminJobResult" ],
            [ "AgentHBReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AgentHBReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AgentHBReq" ],
            [ "AgentHBResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AgentHBResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AgentHBResp" ],
            [ "AlterEdgeReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterEdgeReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterEdgeReq" ],
            [ "AlterSchemaItem", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterSchemaItem.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterSchemaItem" ],
            [ "AlterSchemaOp", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterSchemaOp.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterSchemaOp" ],
            [ "AlterSpaceOp", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterSpaceOp.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterSpaceOp" ],
            [ "AlterSpaceReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterSpaceReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterSpaceReq" ],
            [ "AlterTagReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterTagReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterTagReq" ],
            [ "AlterUserReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterUserReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1AlterUserReq" ],
            [ "BackupMeta", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1BackupMeta.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1BackupMeta" ],
            [ "BalanceTask", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1BalanceTask.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1BalanceTask" ],
            [ "ChangePasswordReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ChangePasswordReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ChangePasswordReq" ],
            [ "ClearSpaceReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ClearSpaceReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ClearSpaceReq" ],
            [ "ColumnDef", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ColumnDef.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ColumnDef" ],
            [ "ColumnTypeDef", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ColumnTypeDef.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ColumnTypeDef" ],
            [ "ConfigItem", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ConfigItem.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ConfigItem" ],
            [ "ConfigMode", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1ConfigMode.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1ConfigMode" ],
            [ "ConfigModule", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1ConfigModule.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1ConfigModule" ],
            [ "Correlativity", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1Correlativity.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1Correlativity" ],
            [ "CreateBackupReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateBackupReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateBackupReq" ],
            [ "CreateBackupResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateBackupResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateBackupResp" ],
            [ "CreateEdgeIndexReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateEdgeIndexReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateEdgeIndexReq" ],
            [ "CreateEdgeReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateEdgeReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateEdgeReq" ],
            [ "CreateFTIndexReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateFTIndexReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateFTIndexReq" ],
            [ "CreateSessionReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateSessionReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateSessionReq" ],
            [ "CreateSessionResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateSessionResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateSessionResp" ],
            [ "CreateSnapshotReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateSnapshotReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateSnapshotReq" ],
            [ "CreateSpaceAsReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateSpaceAsReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateSpaceAsReq" ],
            [ "CreateSpaceReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateSpaceReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateSpaceReq" ],
            [ "CreateTagIndexReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateTagIndexReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateTagIndexReq" ],
            [ "CreateTagReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateTagReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateTagReq" ],
            [ "CreateUserReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateUserReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1CreateUserReq" ],
            [ "DivideZoneReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DivideZoneReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DivideZoneReq" ],
            [ "DropEdgeIndexReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropEdgeIndexReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropEdgeIndexReq" ],
            [ "DropEdgeReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropEdgeReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropEdgeReq" ],
            [ "DropFTIndexReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropFTIndexReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropFTIndexReq" ],
            [ "DropHostsReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropHostsReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropHostsReq" ],
            [ "DropSnapshotReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropSnapshotReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropSnapshotReq" ],
            [ "DropSpaceReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropSpaceReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropSpaceReq" ],
            [ "DropTagIndexReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropTagIndexReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropTagIndexReq" ],
            [ "DropTagReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropTagReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropTagReq" ],
            [ "DropUserReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropUserReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropUserReq" ],
            [ "DropZoneReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropZoneReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1DropZoneReq" ],
            [ "EdgeItem", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1EdgeItem.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1EdgeItem" ],
            [ "ExecResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ExecResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ExecResp" ],
            [ "ExternalServiceType", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1ExternalServiceType.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1ExternalServiceType" ],
            [ "FTIndex", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1FTIndex.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1FTIndex" ],
            [ "GeoShape", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1GeoShape.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1GeoShape" ],
            [ "GetConfigReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetConfigReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetConfigReq" ],
            [ "GetConfigResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetConfigResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetConfigResp" ],
            [ "GetEdgeIndexReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetEdgeIndexReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetEdgeIndexReq" ],
            [ "GetEdgeIndexResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetEdgeIndexResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetEdgeIndexResp" ],
            [ "GetEdgeReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetEdgeReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetEdgeReq" ],
            [ "GetEdgeResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetEdgeResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetEdgeResp" ],
            [ "GetMetaDirInfoReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetMetaDirInfoReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetMetaDirInfoReq" ],
            [ "GetMetaDirInfoResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetMetaDirInfoResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetMetaDirInfoResp" ],
            [ "GetPartsAllocReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetPartsAllocReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetPartsAllocReq" ],
            [ "GetPartsAllocResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetPartsAllocResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetPartsAllocResp" ],
            [ "GetSegmentIdReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetSegmentIdReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetSegmentIdReq" ],
            [ "GetSegmentIdResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetSegmentIdResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetSegmentIdResp" ],
            [ "GetSessionReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetSessionReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetSessionReq" ],
            [ "GetSessionResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetSessionResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetSessionResp" ],
            [ "GetSpaceReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetSpaceReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetSpaceReq" ],
            [ "GetSpaceResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetSpaceResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetSpaceResp" ],
            [ "GetStatsReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetStatsReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetStatsReq" ],
            [ "GetStatsResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetStatsResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetStatsResp" ],
            [ "GetTagIndexReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetTagIndexReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetTagIndexReq" ],
            [ "GetTagIndexResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetTagIndexResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetTagIndexResp" ],
            [ "GetTagReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetTagReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetTagReq" ],
            [ "GetTagResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetTagResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetTagResp" ],
            [ "GetUserRolesReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetUserRolesReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetUserRolesReq" ],
            [ "GetWorkerIdReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetWorkerIdReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetWorkerIdReq" ],
            [ "GetWorkerIdResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetWorkerIdResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetWorkerIdResp" ],
            [ "GetZoneReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetZoneReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetZoneReq" ],
            [ "GetZoneResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetZoneResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GetZoneResp" ],
            [ "GrantRoleReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GrantRoleReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1GrantRoleReq" ],
            [ "HBReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1HBReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1HBReq" ],
            [ "HBResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1HBResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1HBResp" ],
            [ "HostBackupInfo", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1HostBackupInfo.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1HostBackupInfo" ],
            [ "HostItem", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1HostItem.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1HostItem" ],
            [ "HostPair", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1HostPair.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1HostPair" ],
            [ "HostRole", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1HostRole.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1HostRole" ],
            [ "HostStatus", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1HostStatus.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1HostStatus" ],
            [ "ID", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ID.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ID" ],
            [ "IdName", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1IdName.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1IdName" ],
            [ "IndexFieldDef", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1IndexFieldDef.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1IndexFieldDef" ],
            [ "IndexItem", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1IndexItem.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1IndexItem" ],
            [ "IndexParams", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1IndexParams.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1IndexParams" ],
            [ "IndexStatus", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1IndexStatus.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1IndexStatus" ],
            [ "IsolationLevel", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1IsolationLevel.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1IsolationLevel" ],
            [ "JobDesc", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1JobDesc.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1JobDesc" ],
            [ "JobOp", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1JobOp.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1JobOp" ],
            [ "JobStatus", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1JobStatus.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1JobStatus" ],
            [ "JobType", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1JobType.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1JobType" ],
            [ "KillQueryReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1KillQueryReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1KillQueryReq" ],
            [ "LeaderInfo", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1LeaderInfo.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1LeaderInfo" ],
            [ "ListClusterInfoReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListClusterInfoReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListClusterInfoReq" ],
            [ "ListClusterInfoResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListClusterInfoResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListClusterInfoResp" ],
            [ "ListConfigsReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListConfigsReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListConfigsReq" ],
            [ "ListConfigsResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListConfigsResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListConfigsResp" ],
            [ "ListEdgeIndexesReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListEdgeIndexesReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListEdgeIndexesReq" ],
            [ "ListEdgeIndexesResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListEdgeIndexesResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListEdgeIndexesResp" ],
            [ "ListEdgesReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListEdgesReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListEdgesReq" ],
            [ "ListEdgesResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListEdgesResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListEdgesResp" ],
            [ "ListenerInfo", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListenerInfo.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListenerInfo" ],
            [ "ListenerType", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1ListenerType.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1ListenerType" ],
            [ "ListFTIndexesReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListFTIndexesReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListFTIndexesReq" ],
            [ "ListFTIndexesResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListFTIndexesResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListFTIndexesResp" ],
            [ "ListHostsReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListHostsReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListHostsReq" ],
            [ "ListHostsResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListHostsResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListHostsResp" ],
            [ "ListHostType", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1ListHostType.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1ListHostType" ],
            [ "ListIndexStatusReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListIndexStatusReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListIndexStatusReq" ],
            [ "ListIndexStatusResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListIndexStatusResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListIndexStatusResp" ],
            [ "ListListenerReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListListenerReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListListenerReq" ],
            [ "ListListenerResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListListenerResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListListenerResp" ],
            [ "ListPartsReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListPartsReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListPartsReq" ],
            [ "ListPartsResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListPartsResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListPartsResp" ],
            [ "ListRolesReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListRolesReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListRolesReq" ],
            [ "ListRolesResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListRolesResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListRolesResp" ],
            [ "ListServiceClientsReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListServiceClientsReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListServiceClientsReq" ],
            [ "ListServiceClientsResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListServiceClientsResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListServiceClientsResp" ],
            [ "ListSessionsReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListSessionsReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListSessionsReq" ],
            [ "ListSessionsResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListSessionsResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListSessionsResp" ],
            [ "ListSnapshotsReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListSnapshotsReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListSnapshotsReq" ],
            [ "ListSnapshotsResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListSnapshotsResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListSnapshotsResp" ],
            [ "ListSpacesReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListSpacesReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListSpacesReq" ],
            [ "ListSpacesResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListSpacesResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListSpacesResp" ],
            [ "ListTagIndexesReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListTagIndexesReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListTagIndexesReq" ],
            [ "ListTagIndexesResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListTagIndexesResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListTagIndexesResp" ],
            [ "ListTagsReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListTagsReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListTagsReq" ],
            [ "ListTagsResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListTagsResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListTagsResp" ],
            [ "ListUsersReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListUsersReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListUsersReq" ],
            [ "ListUsersResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListUsersResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListUsersResp" ],
            [ "ListZonesReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListZonesReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListZonesReq" ],
            [ "ListZonesResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListZonesResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ListZonesResp" ],
            [ "MergeZoneReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1MergeZoneReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1MergeZoneReq" ],
            [ "MetaService", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1MetaService.html", [
              [ "AsyncIface", "interfacecom_1_1vesoft_1_1nebula_1_1meta_1_1MetaService_1_1AsyncIface.html", "interfacecom_1_1vesoft_1_1nebula_1_1meta_1_1MetaService_1_1AsyncIface" ],
              [ "Iface", "interfacecom_1_1vesoft_1_1nebula_1_1meta_1_1MetaService_1_1Iface.html", "interfacecom_1_1vesoft_1_1nebula_1_1meta_1_1MetaService_1_1Iface" ]
            ] ],
            [ "PartInfo", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1PartInfo.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1PartInfo" ],
            [ "PartItem", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1PartItem.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1PartItem" ],
            [ "PartitionList", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1PartitionList.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1PartitionList" ],
            [ "QueryDesc", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1QueryDesc.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1QueryDesc" ],
            [ "QueryStatus", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1QueryStatus.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1QueryStatus" ],
            [ "RebuildIndexReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RebuildIndexReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RebuildIndexReq" ],
            [ "RegConfigReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RegConfigReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RegConfigReq" ],
            [ "RemoveListenerReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RemoveListenerReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RemoveListenerReq" ],
            [ "RemoveSessionReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RemoveSessionReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RemoveSessionReq" ],
            [ "RemoveSessionResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RemoveSessionResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RemoveSessionResp" ],
            [ "RenameZoneReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RenameZoneReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RenameZoneReq" ],
            [ "ReportTaskReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ReportTaskReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ReportTaskReq" ],
            [ "RestoreMetaReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RestoreMetaReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RestoreMetaReq" ],
            [ "RestoreMetaResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RestoreMetaResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RestoreMetaResp" ],
            [ "RevokeRoleReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RevokeRoleReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RevokeRoleReq" ],
            [ "RoleItem", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RoleItem.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1RoleItem" ],
            [ "RoleType", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1RoleType.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1RoleType" ],
            [ "SaveGraphVersionReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SaveGraphVersionReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SaveGraphVersionReq" ],
            [ "SaveGraphVersionResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SaveGraphVersionResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SaveGraphVersionResp" ],
            [ "Schema", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1Schema.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1Schema" ],
            [ "SchemaProp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SchemaProp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SchemaProp" ],
            [ "ServiceClient", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ServiceClient.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ServiceClient" ],
            [ "ServiceInfo", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ServiceInfo.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1ServiceInfo" ],
            [ "Session", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1Session.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1Session" ],
            [ "SetConfigReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SetConfigReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SetConfigReq" ],
            [ "SignInServiceReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SignInServiceReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SignInServiceReq" ],
            [ "SignOutServiceReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SignOutServiceReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SignOutServiceReq" ],
            [ "Snapshot", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1Snapshot.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1Snapshot" ],
            [ "SnapshotStatus", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1SnapshotStatus.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1SnapshotStatus" ],
            [ "SpaceBackupInfo", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SpaceBackupInfo.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SpaceBackupInfo" ],
            [ "SpaceDesc", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SpaceDesc.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SpaceDesc" ],
            [ "SpaceItem", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SpaceItem.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1SpaceItem" ],
            [ "StatsItem", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1StatsItem.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1StatsItem" ],
            [ "TagItem", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1TagItem.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1TagItem" ],
            [ "TaskDesc", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1TaskDesc.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1TaskDesc" ],
            [ "TaskResult", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1TaskResult.html", "enumcom_1_1vesoft_1_1nebula_1_1meta_1_1TaskResult" ],
            [ "UpdateSessionsReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1UpdateSessionsReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1UpdateSessionsReq" ],
            [ "UpdateSessionsResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1UpdateSessionsResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1UpdateSessionsResp" ],
            [ "UserItem", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1UserItem.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1UserItem" ],
            [ "VerifyClientVersionReq", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1VerifyClientVersionReq.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1VerifyClientVersionReq" ],
            [ "VerifyClientVersionResp", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1VerifyClientVersionResp.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1VerifyClientVersionResp" ],
            [ "Zone", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1Zone.html", "classcom_1_1vesoft_1_1nebula_1_1meta_1_1Zone" ]
          ] ],
          [ "storage", "namespacecom_1_1vesoft_1_1nebula_1_1storage.html", [
            [ "AddEdgesRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AddEdgesRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AddEdgesRequest" ],
            [ "AddLearnerReq", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AddLearnerReq.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AddLearnerReq" ],
            [ "AddPartReq", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AddPartReq.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AddPartReq" ],
            [ "AddTaskRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AddTaskRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AddTaskRequest" ],
            [ "AddTaskResp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AddTaskResp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AddTaskResp" ],
            [ "AddVerticesRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AddVerticesRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AddVerticesRequest" ],
            [ "AdminExecResp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AdminExecResp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1AdminExecResp" ],
            [ "BlockingSignRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1BlockingSignRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1BlockingSignRequest" ],
            [ "BlockingSignResp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1BlockingSignResp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1BlockingSignResp" ],
            [ "CatchUpDataReq", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1CatchUpDataReq.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1CatchUpDataReq" ],
            [ "ChainAddEdgesRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ChainAddEdgesRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ChainAddEdgesRequest" ],
            [ "ChainDeleteEdgesRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ChainDeleteEdgesRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ChainDeleteEdgesRequest" ],
            [ "ChainUpdateEdgeRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ChainUpdateEdgeRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ChainUpdateEdgeRequest" ],
            [ "CheckPeersReq", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1CheckPeersReq.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1CheckPeersReq" ],
            [ "ClearSpaceReq", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ClearSpaceReq.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ClearSpaceReq" ],
            [ "ClearSpaceResp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ClearSpaceResp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ClearSpaceResp" ],
            [ "CreateCPRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1CreateCPRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1CreateCPRequest" ],
            [ "CreateCPResp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1CreateCPResp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1CreateCPResp" ],
            [ "DeleteEdgesRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1DeleteEdgesRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1DeleteEdgesRequest" ],
            [ "DeleteTagsRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1DeleteTagsRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1DeleteTagsRequest" ],
            [ "DeleteVerticesRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1DeleteVerticesRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1DeleteVerticesRequest" ],
            [ "DelTags", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1DelTags.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1DelTags" ],
            [ "DropCPRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1DropCPRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1DropCPRequest" ],
            [ "DropCPResp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1DropCPResp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1DropCPResp" ],
            [ "EdgeDirection", "enumcom_1_1vesoft_1_1nebula_1_1storage_1_1EdgeDirection.html", "enumcom_1_1vesoft_1_1nebula_1_1storage_1_1EdgeDirection" ],
            [ "EdgeKey", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1EdgeKey.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1EdgeKey" ],
            [ "EdgeProp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1EdgeProp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1EdgeProp" ],
            [ "EngineSignType", "enumcom_1_1vesoft_1_1nebula_1_1storage_1_1EngineSignType.html", "enumcom_1_1vesoft_1_1nebula_1_1storage_1_1EngineSignType" ],
            [ "ExecResponse", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ExecResponse.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ExecResponse" ],
            [ "Expr", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1Expr.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1Expr" ],
            [ "GetDstBySrcRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetDstBySrcRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetDstBySrcRequest" ],
            [ "GetDstBySrcResponse", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetDstBySrcResponse.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetDstBySrcResponse" ],
            [ "GetLeaderPartsResp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetLeaderPartsResp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetLeaderPartsResp" ],
            [ "GetLeaderReq", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetLeaderReq.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetLeaderReq" ],
            [ "GetNeighborsRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetNeighborsRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetNeighborsRequest" ],
            [ "GetNeighborsResponse", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetNeighborsResponse.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetNeighborsResponse" ],
            [ "GetPropRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetPropRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetPropRequest" ],
            [ "GetPropResponse", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetPropResponse.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetPropResponse" ],
            [ "GetUUIDReq", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetUUIDReq.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetUUIDReq" ],
            [ "GetUUIDResp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetUUIDResp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GetUUIDResp" ],
            [ "GraphStorageService", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1GraphStorageService.html", [
              [ "AsyncIface", "interfacecom_1_1vesoft_1_1nebula_1_1storage_1_1GraphStorageService_1_1AsyncIface.html", "interfacecom_1_1vesoft_1_1nebula_1_1storage_1_1GraphStorageService_1_1AsyncIface" ],
              [ "Iface", "interfacecom_1_1vesoft_1_1nebula_1_1storage_1_1GraphStorageService_1_1Iface.html", "interfacecom_1_1vesoft_1_1nebula_1_1storage_1_1GraphStorageService_1_1Iface" ]
            ] ],
            [ "IndexColumnHint", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1IndexColumnHint.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1IndexColumnHint" ],
            [ "IndexQueryContext", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1IndexQueryContext.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1IndexQueryContext" ],
            [ "IndexSpec", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1IndexSpec.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1IndexSpec" ],
            [ "InternalStorageService", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1InternalStorageService.html", [
              [ "AsyncIface", "interfacecom_1_1vesoft_1_1nebula_1_1storage_1_1InternalStorageService_1_1AsyncIface.html", "interfacecom_1_1vesoft_1_1nebula_1_1storage_1_1InternalStorageService_1_1AsyncIface" ],
              [ "Iface", "interfacecom_1_1vesoft_1_1nebula_1_1storage_1_1InternalStorageService_1_1Iface.html", "interfacecom_1_1vesoft_1_1nebula_1_1storage_1_1InternalStorageService_1_1Iface" ]
            ] ],
            [ "KVGetRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1KVGetRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1KVGetRequest" ],
            [ "KVGetResponse", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1KVGetResponse.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1KVGetResponse" ],
            [ "KVPutRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1KVPutRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1KVPutRequest" ],
            [ "KVRemoveRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1KVRemoveRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1KVRemoveRequest" ],
            [ "ListClusterInfoReq", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ListClusterInfoReq.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ListClusterInfoReq" ],
            [ "ListClusterInfoResp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ListClusterInfoResp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ListClusterInfoResp" ],
            [ "LookupAndTraverseRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1LookupAndTraverseRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1LookupAndTraverseRequest" ],
            [ "LookupIndexRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1LookupIndexRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1LookupIndexRequest" ],
            [ "LookupIndexResp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1LookupIndexResp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1LookupIndexResp" ],
            [ "MemberChangeReq", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1MemberChangeReq.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1MemberChangeReq" ],
            [ "NewEdge", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1NewEdge.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1NewEdge" ],
            [ "NewTag", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1NewTag.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1NewTag" ],
            [ "NewVertex", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1NewVertex.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1NewVertex" ],
            [ "OrderBy", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1OrderBy.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1OrderBy" ],
            [ "OrderDirection", "enumcom_1_1vesoft_1_1nebula_1_1storage_1_1OrderDirection.html", "enumcom_1_1vesoft_1_1nebula_1_1storage_1_1OrderDirection" ],
            [ "PartitionResult", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1PartitionResult.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1PartitionResult" ],
            [ "RebuildIndexRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1RebuildIndexRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1RebuildIndexRequest" ],
            [ "RemovePartReq", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1RemovePartReq.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1RemovePartReq" ],
            [ "RequestCommon", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1RequestCommon.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1RequestCommon" ],
            [ "ResponseCommon", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ResponseCommon.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ResponseCommon" ],
            [ "ScanCursor", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ScanCursor.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ScanCursor" ],
            [ "ScanEdgeRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ScanEdgeRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ScanEdgeRequest" ],
            [ "ScanResponse", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ScanResponse.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ScanResponse" ],
            [ "ScanType", "enumcom_1_1vesoft_1_1nebula_1_1storage_1_1ScanType.html", "enumcom_1_1vesoft_1_1nebula_1_1storage_1_1ScanType" ],
            [ "ScanVertexRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ScanVertexRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1ScanVertexRequest" ],
            [ "StatProp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1StatProp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1StatProp" ],
            [ "StatType", "enumcom_1_1vesoft_1_1nebula_1_1storage_1_1StatType.html", "enumcom_1_1vesoft_1_1nebula_1_1storage_1_1StatType" ],
            [ "StopTaskRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1StopTaskRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1StopTaskRequest" ],
            [ "StopTaskResp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1StopTaskResp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1StopTaskResp" ],
            [ "StorageAdminService", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1StorageAdminService.html", [
              [ "AsyncIface", "interfacecom_1_1vesoft_1_1nebula_1_1storage_1_1StorageAdminService_1_1AsyncIface.html", "interfacecom_1_1vesoft_1_1nebula_1_1storage_1_1StorageAdminService_1_1AsyncIface" ],
              [ "Iface", "interfacecom_1_1vesoft_1_1nebula_1_1storage_1_1StorageAdminService_1_1Iface.html", "interfacecom_1_1vesoft_1_1nebula_1_1storage_1_1StorageAdminService_1_1Iface" ]
            ] ],
            [ "TaskPara", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1TaskPara.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1TaskPara" ],
            [ "TransLeaderReq", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1TransLeaderReq.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1TransLeaderReq" ],
            [ "TraverseSpec", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1TraverseSpec.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1TraverseSpec" ],
            [ "UpdatedProp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1UpdatedProp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1UpdatedProp" ],
            [ "UpdateEdgeRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1UpdateEdgeRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1UpdateEdgeRequest" ],
            [ "UpdateResponse", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1UpdateResponse.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1UpdateResponse" ],
            [ "UpdateVertexRequest", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1UpdateVertexRequest.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1UpdateVertexRequest" ],
            [ "VertexProp", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1VertexProp.html", "classcom_1_1vesoft_1_1nebula_1_1storage_1_1VertexProp" ]
          ] ],
          [ "util", null, [
            [ "ReflectUtil", "classcom_1_1vesoft_1_1nebula_1_1util_1_1ReflectUtil.html", null ],
            [ "SslUtil", "classcom_1_1vesoft_1_1nebula_1_1util_1_1SslUtil.html", null ]
          ] ],
          [ "CheckpointInfo", "classcom_1_1vesoft_1_1nebula_1_1CheckpointInfo.html", "classcom_1_1vesoft_1_1nebula_1_1CheckpointInfo" ],
          [ "Constants", "classcom_1_1vesoft_1_1nebula_1_1Constants.html", null ],
          [ "Coordinate", "classcom_1_1vesoft_1_1nebula_1_1Coordinate.html", "classcom_1_1vesoft_1_1nebula_1_1Coordinate" ],
          [ "DataSet", "classcom_1_1vesoft_1_1nebula_1_1DataSet.html", "classcom_1_1vesoft_1_1nebula_1_1DataSet" ],
          [ "Date", "classcom_1_1vesoft_1_1nebula_1_1Date.html", "classcom_1_1vesoft_1_1nebula_1_1Date" ],
          [ "DateTime", "classcom_1_1vesoft_1_1nebula_1_1DateTime.html", "classcom_1_1vesoft_1_1nebula_1_1DateTime" ],
          [ "DirInfo", "classcom_1_1vesoft_1_1nebula_1_1DirInfo.html", "classcom_1_1vesoft_1_1nebula_1_1DirInfo" ],
          [ "Duration", "classcom_1_1vesoft_1_1nebula_1_1Duration.html", "classcom_1_1vesoft_1_1nebula_1_1Duration" ],
          [ "Edge", "classcom_1_1vesoft_1_1nebula_1_1Edge.html", "classcom_1_1vesoft_1_1nebula_1_1Edge" ],
          [ "ErrorCode", "enumcom_1_1vesoft_1_1nebula_1_1ErrorCode.html", "enumcom_1_1vesoft_1_1nebula_1_1ErrorCode" ],
          [ "Geography", "classcom_1_1vesoft_1_1nebula_1_1Geography.html", "classcom_1_1vesoft_1_1nebula_1_1Geography" ],
          [ "HostAddr", "classcom_1_1vesoft_1_1nebula_1_1HostAddr.html", "classcom_1_1vesoft_1_1nebula_1_1HostAddr" ],
          [ "KeyValue", "classcom_1_1vesoft_1_1nebula_1_1KeyValue.html", "classcom_1_1vesoft_1_1nebula_1_1KeyValue" ],
          [ "LineString", "classcom_1_1vesoft_1_1nebula_1_1LineString.html", "classcom_1_1vesoft_1_1nebula_1_1LineString" ],
          [ "LogEntry", "classcom_1_1vesoft_1_1nebula_1_1LogEntry.html", "classcom_1_1vesoft_1_1nebula_1_1LogEntry" ],
          [ "LogInfo", "classcom_1_1vesoft_1_1nebula_1_1LogInfo.html", "classcom_1_1vesoft_1_1nebula_1_1LogInfo" ],
          [ "NList", "classcom_1_1vesoft_1_1nebula_1_1NList.html", "classcom_1_1vesoft_1_1nebula_1_1NList" ],
          [ "NMap", "classcom_1_1vesoft_1_1nebula_1_1NMap.html", "classcom_1_1vesoft_1_1nebula_1_1NMap" ],
          [ "NSet", "classcom_1_1vesoft_1_1nebula_1_1NSet.html", "classcom_1_1vesoft_1_1nebula_1_1NSet" ],
          [ "NullType", "enumcom_1_1vesoft_1_1nebula_1_1NullType.html", "enumcom_1_1vesoft_1_1nebula_1_1NullType" ],
          [ "Path", "classcom_1_1vesoft_1_1nebula_1_1Path.html", "classcom_1_1vesoft_1_1nebula_1_1Path" ],
          [ "Point", "classcom_1_1vesoft_1_1nebula_1_1Point.html", "classcom_1_1vesoft_1_1nebula_1_1Point" ],
          [ "Polygon", "classcom_1_1vesoft_1_1nebula_1_1Polygon.html", "classcom_1_1vesoft_1_1nebula_1_1Polygon" ],
          [ "PropertyType", "enumcom_1_1vesoft_1_1nebula_1_1PropertyType.html", "enumcom_1_1vesoft_1_1nebula_1_1PropertyType" ],
          [ "Row", "classcom_1_1vesoft_1_1nebula_1_1Row.html", "classcom_1_1vesoft_1_1nebula_1_1Row" ],
          [ "SchemaID", "classcom_1_1vesoft_1_1nebula_1_1SchemaID.html", "classcom_1_1vesoft_1_1nebula_1_1SchemaID" ],
          [ "Step", "classcom_1_1vesoft_1_1nebula_1_1Step.html", "classcom_1_1vesoft_1_1nebula_1_1Step" ],
          [ "Tag", "classcom_1_1vesoft_1_1nebula_1_1Tag.html", "classcom_1_1vesoft_1_1nebula_1_1Tag" ],
          [ "Time", "classcom_1_1vesoft_1_1nebula_1_1Time.html", "classcom_1_1vesoft_1_1nebula_1_1Time" ],
          [ "Value", "classcom_1_1vesoft_1_1nebula_1_1Value.html", "classcom_1_1vesoft_1_1nebula_1_1Value" ],
          [ "Vertex", "classcom_1_1vesoft_1_1nebula_1_1Vertex.html", "classcom_1_1vesoft_1_1nebula_1_1Vertex" ]
        ] ]
      ] ]
    ] ],
    [ "AppendLogRequest", "classAppendLogRequest.html", "classAppendLogRequest" ],
    [ "AppendLogResponse", "classAppendLogResponse.html", "classAppendLogResponse" ],
    [ "AskForVoteRequest", "classAskForVoteRequest.html", "classAskForVoteRequest" ],
    [ "AskForVoteResponse", "classAskForVoteResponse.html", "classAskForVoteResponse" ],
    [ "GetStateRequest", "classGetStateRequest.html", "classGetStateRequest" ],
    [ "GetStateResponse", "classGetStateResponse.html", "classGetStateResponse" ],
    [ "HeartbeatRequest", "classHeartbeatRequest.html", "classHeartbeatRequest" ],
    [ "HeartbeatResponse", "classHeartbeatResponse.html", "classHeartbeatResponse" ],
    [ "RaftexService", "classRaftexService.html", [
      [ "AsyncIface", "interfaceRaftexService_1_1AsyncIface.html", "interfaceRaftexService_1_1AsyncIface" ],
      [ "Iface", "interfaceRaftexService_1_1Iface.html", "interfaceRaftexService_1_1Iface" ]
    ] ],
    [ "RaftLogEntry", "classRaftLogEntry.html", "classRaftLogEntry" ],
    [ "Role", "enumRole.html", "enumRole" ],
    [ "SendSnapshotRequest", "classSendSnapshotRequest.html", "classSendSnapshotRequest" ],
    [ "SendSnapshotResponse", "classSendSnapshotResponse.html", "classSendSnapshotResponse" ],
    [ "Status", "enumStatus.html", "enumStatus" ]
];