name: Generate API reference via Doxygen and push to GitHub Pages
env:
  # Specify the SDK version based on which the API reference is generated
  output_version: release-3.6
  # Specify the doc version to which the API reference belongs
  doc_version: 3.6.0
on:
  push:
    branches:
        # Remember to update the version number
      - release-3.6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # fetch all commits/branches for gitversion

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    # Generate HTML files in the directory ${{ env.output_version}}/html    
    - name: Generate Documentation
      run: |
        echo "OUTPUT_DIRECTORY=${{ env.output_version}}" >> doxygen-config
        doxygen doxygen-config

    # Deploy the generated HTML files (under the directory ${{ env.output_version}}/html) to the gh-pages branch (into the directory ${{ env.output_version}})
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.output_version}}/html
        destination_dir: ${{ env.output_version}}

    # - name: show gh-pages branch
    #   run: |
    #     git branch
    #     git checkout .
    #     git checkout gh-pages
   
    # # Compresses HTML files under the directory ${{ env.output_version}} into a tar.gz file
    # - name: compress api reference
    #   run: |
    #     tar -zcvf ${{ env.output_version}}.tar.gz ${{ env.output_version}}
        
    # - name: transfer api reference
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: 20.163.77.63
    #     username: azureuser
    #     password: ${{ secrets.ENSITE_PASSWORD }}
    #     port: 404
    #     source: ${{ env.output_version}}.tar.gz
    #     # Return error if the target doc version does not already exist
    #     target: /var/www/ent-docs/${{ env.doc_version}}/

    # - name: uncompress ap reference
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: 20.163.77.63
    #     username: azureuser
    #     password: ${{ secrets.ENSITE_PASSWORD }}
    #     port: 404
    #     script: |
    #       mkdir -p /var/www/ent-docs/${{ env.doc_version}}/api/java/
    #       tar -zxf /var/www/ent-docs/${{ env.doc_version}}/${{ env.output_version}}.tar.gz -C /var/www/ent-docs/${{ env.doc_version}}/api/java/


