name: Generate API reference via Doxygen and push to GitHub Pages
env:
  # Specify the SDK version based on which the API reference is generated
  # output_version: release-3.6
  # Specify the doc version to which the API reference belongs
  doc_version: 3.6.0
on:
  push:
    branches:
        # Remember to update the version number
      - release-3.6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # fetch all commits/branches for gitversion

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    # Generate HTML files   
    - name: Generate Documentation
      run: |
        echo "OUTPUT_DIRECTORY=${{ steps.extract_branch.outputs.branch }}" >> doxygen-config
        doxygen doxygen-config

    # Deploy the generated HTML files to the gh-pages branch
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.extract_branch.outputs.branch }}/html
        destination_dir: ${{ steps.extract_branch.outputs.branch }}

    # - name: show gh-pages branch
    #   run: |
    #     git branch
    #     git checkout .
    #     git checkout gh-pages
   
    # # Compresses HTML files into a tar.gz file
    # - name: compress api reference
    #   run: |
    #     tar -zcvf ${{ steps.extract_branch.outputs.branch }}.tar.gz ${{ steps.extract_branch.outputs.branch }}
        
    # - name: transfer api reference
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: 20.163.77.63
    #     username: azureuser
    #     password: ${{ secrets.ENSITE_PASSWORD }}
    #     port: 404
    #     source: ${{ steps.extract_branch.outputs.branch }}.tar.gz
    #     # Return error if the target doc version does not already exist
    #     target: /var/www/ent-docs/${{ env.doc_version }}/

    # - name: uncompress ap reference
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: 20.163.77.63
    #     username: azureuser
    #     password: ${{ secrets.ENSITE_PASSWORD }}
    #     port: 404
    #     script: |
    #       mkdir -p /var/www/ent-docs/${{ env.doc_version}}/api/java/
    #       tar -zxf /var/www/ent-docs/${{ env.doc_version}}/${{ steps.extract_branch.outputs.branch }}.tar.gz -C /var/www/ent-docs/${{ env.doc_version}}/api/java/


