name: Generate API reference via Doxygen and push to GitHub Pages
env:
  # Remember to update the version number
  output_version: release-3.6
on:
    push:
        branches:
        # Remember to update the version number
          - release-3.6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # fetch all commits/branches for gitversion

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Generate Documentation
      run: |
        echo "OUTPUT_DIRECTORY=Java-${{ env.output_version}}" >> doxygen-config
        doxygen doxygen-config

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Java-${{ env.output_version}}/html
        destination_dir: ${{ env.output_version}}